name: Send Request with curl
on: [workflow_dispatch, push]

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET request to Microsoft
        run: |
          curl -v -L "https://www.microsoft.com" \
            -H "User-Agent: GitHub-Action" \
            --max-time 30
